app_rest:
    resource: "@AppRestBundle/Controller/"
    type:     annotation
    prefix:   /

app_common:
    resource: "@AppCommonBundle/Controller/"
    type:     annotation
    prefix:   /

app_t360:
    resource: "@AppT360Bundle/Controller/"
    type:     annotation
    prefix:   /

data_layer:
    resource: "@DataLayerBundle/Controller/"
    type:     annotation
    prefix:   /

# app/config/routing.yml

# ...

login:
    pattern:   /login
    defaults:  { _controller: OCUserBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout

