# app/config/security.yml

security:
    encoders:
        DataLayerBundle\Entity\Employees:
          algorithm:   sha1
          iterations: 1
          encode_as_base64: false

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: DataLayerBundle\Entity\Employees, property: username }


    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        rest_login:
                    # Cette expression régulière permet de prendre /login (mais pas /login_check !)
                    pattern:   ^/service*
                    anonymous: true # On autorise alors les anonymes sur ce pare-feu
        register_login:
                    # Cette expression régulière permet de prendre /login (mais pas /login_check !)
                    pattern:   ^/registerbegin*
                    anonymous: true # On autorise alors les anonymes sur ce pare-feu

        main_login:
            # Cette expression régulière permet de prendre /login (mais pas /login_check !)
            pattern:   ^/login$
            anonymous: true # On autorise alors les anonymes sur ce pare-feu



        main:
            pattern: ^/
            anonymous: false
            provider: main
            form_login:
                login_path: login
                check_path: login_check
                default_target_path: /t360evaluations
            logout:
                path:   logout
                target: /login

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }