parameters:
    employeeServiceclass: DataLayerBundle\Managers\GestionEmployee
    t360evaluationServiceclass: DataLayerBundle\Managers\GestionT360Evaluation
    t360questionsServiceclass: DataLayerBundle\Managers\GestionT360Questions
    t360reponseServiceclass: DataLayerBundle\Managers\GestionT360Reponses
    employeeServiceclass: DataLayerBundle\Managers\GestionEmployee
    directionsServiceclass: DataLayerBundle\Managers\GestionDirections
    directionsPosteServiceclass: DataLayerBundle\Managers\GestionDirectionsPostes
    postesServiceclass: DataLayerBundle\Managers\GestionPostes

services:
    employee.service:
        class: "%employeeServiceclass%"
        arguments: ["@doctrine.orm.entity_manager"]

    t360evaluation.service:
        class: "%t360evaluationServiceclass%"
        arguments: ["@doctrine.orm.entity_manager"]

    t360question.service:
        class: "%t360questionsServiceclass%"
        arguments: ["@doctrine.orm.entity_manager"]

    t360reponse.service:
            class: "%t360reponseServiceclass%"
            arguments: ["@doctrine.orm.entity_manager"]

    employee.service:
            class: "%employeeServiceclass%"
            arguments: ["@doctrine.orm.entity_manager"]

    directions.service:
                class: "%directionsServiceclass%"
                arguments: ["@doctrine.orm.entity_manager"]

    directionspostes.service:
                    class: "%directionsPosteServiceclass%"
                    arguments: ["@doctrine.orm.entity_manager"]

    postes.service:
                class: "%postesServiceclass%"
                arguments: ["@doctrine.orm.entity_manager"]